version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: open-webui_web_1
      APP_PORT: 8080
      PROXY_AUTH_ADD: "false"

  web:
    image: ghcr.io/open-webui/open-webui:v0.5.19@sha256:6bcdb458af47c555f2b0e6f39275ba128d3c48197c118f6fd58fec2db612bc74
    volumes:
      - ${APP_DATA_DIR}/data/open-webui:/app/backend/data
    environment:
      # Exported from ollama app, which is currently a required dependency.
      # This will need to change once optional dependencies are supported.
      OLLAMA_BASE_URL: $APP_OLLAMA_URL
    restart: on-failure
