version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: qbittorrent_server_1
      APP_PORT: 8080
      PROXY_AUTH_ADD: "false"

  server:
    image: hotio/qbittorrent:release-5.0.2@sha256:09993fc93740731f48416969506c91bcdc16dc88b197b4e6a100896e2b7f58d9
    environment:
      - PUID=1000
      - PGID=1000
      # - UMASK=002
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      # /app/qBittorrent/downloads is the default path set in qBittorrent
      - ${UMBREL_ROOT}/data/storage/downloads:/app/qBittorrent/downloads
    restart: on-failure