version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: rotki_web_1
      APP_PORT: 80

  web:
    image: rotki/rotki:v1.36.1@sha256:253ce6158e6cfc406401d504dc7e074f916a4b1104b803072b48b16bd720fdfa
    restart: on-failure
    stop_grace_period: 1m
    init: true
    volumes:
      - ${APP_DATA_DIR}/data/data:/data
      - ${APP_DATA_DIR}/data/logs:/logs