version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mealie_web_1
      APP_PORT: 9000
      PROXY_AUTH_WHITELIST: "/api/*"

  web:
    image: ghcr.io/mealie-recipes/mealie:v2.3.0@sha256:562ba8b1c98fbfa98a019ab6e0e45c88dae9a2e9a858ec4eac8f6321e46e9227
    restart: on-failure
    environment:
      # Allow additional user sign-up without token
      ALLOW_SIGNUP: "true"
      PUID: 1000
      PGID: 1000
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
    volumes:
      - ${APP_DATA_DIR}/data:/app/data