version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: element_web_1
      APP_PORT: 80

  web:
    image: vectorim/element-web:v1.11.87@sha256:7d3f7970bd00411c5ae315a2c6b05506cbdf1b33b4b0120cdc8d4127c60d3a1b
    # NGINX parent container requires root
    # user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m