version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: lobe-chat_app_1
      APP_PORT: 3210

  app:
    image: lobehub/lobe-chat:v1.51.3@sha256:07f9f9a094c9694633f9a0a7eb50628060306881c92d0ff8c57a6b24036d95da
    restart: on-failure
    user: "1000:1000"