services:

  app_proxy:
    environment:
      APP_HOST: mosquitto_broker_1
      APP_PORT: 9001

  broker:
    image: eclipse-mosquitto:2.0.20@sha256:21421af7b32bf9ce508e9090c8eb13bb81f410ca778dc205506180a6f862d0eb
    restart: on-failure
    ports:
      - '1883:1883'
    volumes:
      - ${APP_DATA_DIR}/data/config:/mosquitto/config:rw
      - ${APP_DATA_DIR}/data/mosquitto:/mosquitto/data:rw
      - ${APP_DATA_DIR}/data/log:/mosquitto/log:rw
      - ${APP_DATA_DIR}/data/www:/mosquitto/www:r
    user: "1000:1000"
