version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: pocketbase_app_1
      APP_PORT: 8090
      PROXY_AUTH_ADD: "false"
  
  app:
    image: ghcr.io/muchobien/pocketbase:0.24.3@sha256:f9750591a9e1a96f3a26d341172db31157c43d8a8e8570f29bcc56d3abf6ac6e
    # pocketbase needs to run as root
    # user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data/data:/pb_data
      - ${APP_DATA_DIR}/data/public:/pb_public
      - ${APP_DATA_DIR}/data/hooks:/pb_hooks
      - ${APP_DATA_DIR}/data/migrations:/pb_migrations