version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: budibase_budibase_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"

  budibase:
    image: budibase/budibase:3.2.25@sha256:a71230c07a618a20041515e1ab3bad156c4051757694ebf942a7d91932bb7721
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data/budibase:/data
    environment:
      JWT_SECRET: ${APP_SEED}