version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: bazarr_server_1
      APP_PORT: 6767
      PROXY_AUTH_WHITELIST: "/api/*"

  server:
    image: linuxserver/bazarr:1.4.5@sha256:a602332403fcac11717c37ba14fb1852eb0b752d95db67915914fc9dd9e653a8
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
    restart: on-failure