version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: stirling-pdf_app_1
      APP_PORT: 8080
      PROXY_AUTH_WHITELIST: "/api/*"
  
  app:
    image: stirlingtools/stirling-pdf:0.39.0@sha256:2ebe1c8f1bc92235623c6903b5f3310de43159da4b67ca308b820b600b1bf988
    # Stirling PDF does not work with a custom user
    #user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      # Required for extra OCR languages
      - ${APP_DATA_DIR}/data/tessdata:/usr/share/tessdata
      - ${APP_DATA_DIR}/data/configs:/configs
      - ${APP_DATA_DIR}/data/logs:/logs
    environment:
      # Not needed as Umbrel authenticates the user
      DOCKER_ENABLE_SECURITY: "false"
      INSTALL_BOOK_AND_ADVANCED_HTML_OPS: "true"
      LANGS: ALL