version: "3.7"

services:
   app_proxy:
      environment:
         APP_HOST: minio_web_1
         APP_PORT: 9011
         PROXY_AUTH_ADD: "false"

   web:
      image: quay.io/minio/minio:RELEASE.2025-01-18T00-31-37Z@sha256:442993fd0ef161f17aaaf5d6a5a0ed4d36edc577e28e327813d3be1733a59aff
      restart: on-failure
      user: "1000:1000"
      stop_grace_period: 1m
      ports:
         # MinIO Api Server Port
         - "9010:9000"
      command: ["server", "/data"]
      volumes:
         - ${APP_DATA_DIR}/data/minio:/data
      environment:
         MINIO_ROOT_USER: "umbrel"
         MINIO_ROOT_PASSWORD: "$APP_PASSWORD"
         MINIO_CONSOLE_ADDRESS: ":9011"