version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: autobrr_web_1
      APP_PORT: 7474
      PROXY_AUTH_ADD: "false"

  web:
    image: ghcr.io/autobrr/autobrr:v1.52.0@sha256:329307d54fcfc8a79536a2619b5b78a834706dd97ea34c50180f52591fe5ce01
    restart: on-failure
    stop_grace_period: 1m
    user: "1000:1000"
    volumes:
      - ${APP_DATA_DIR}/data:/config