version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: autobrr_web_1
      APP_PORT: 7474
      PROXY_AUTH_ADD: "false"

  web:
    image: ghcr.io/autobrr/autobrr:v1.53.0@sha256:0c3f93c653cfc8a20e722bd26a5d597a496c9ba714300ba7974a5aeb19bd6e31
    restart: on-failure
    stop_grace_period: 1m
    user: "1000:1000"
    volumes:
      - ${APP_DATA_DIR}/data:/config