version: "3.7"

services:
  server:
    image: esphome/esphome:2024.11.2@sha256:addd04021aa25cc1ebd96e3e18072b9398b4b6bf7c8322166b8bcf247ca78681
    network_mode: host
    volumes:
      - ${APP_DATA_DIR}/data:/config
    restart: on-failure