version: "3.7"

services:
  server:
    image: esphome/esphome:2024.11.3@sha256:92d8744930833bf9b3b7fc7f18fcae1d256b6cc6fa234fd961ae79b20c49b393
    network_mode: host
    volumes:
      - ${APP_DATA_DIR}/data:/config
    restart: on-failure