version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: whoogle-search_web_1
      APP_PORT: 6420

  web:
    image: benbusby/whoogle-search:0.9.2@sha256:9dbaafaee01119c8c82c518138642e0a017fa2b2fc6ec28cb4a446700693196f
    restart: on-failure
    stop_grace_period: 1m
    init: true
    user: "927:927"
    environment:
      EXPOSE_PORT: 6420